---
title: Getting started with Node-RED
hero_image: images/banner.png
description: In this resource you will learn how to use Node-RED to control Raspberry
  Pi GPIO pins
original_url: https://raspberrypi.org/learning/getting-started-with-node-red
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: Getting started with Node-RED
- title: GPIO pins
  completion:
  - engaged
- title: Wire up the LED
- title: Start Node-RED
- title: Connecting to a GPIO pin
- title: Injecting messages
- title: Deploying the flow
- title: Debugging your flow
- title: Adding a button
  completion:
  - internal
- title: What next?
